import express from 'express';import cors from 'cors';import {createServer} from 'node:http';import {randomUUID} from 'node:crypto';import {Server,Room,type Client} from '@colyseus/core';import {WebSocketTransport} from '@colyseus/ws-transport';import {Schema} from '@colyseus/schema';import {createClient} from '@supabase/supabase-js';
import {Game,initPhysics,type Input,type Action} from '../../packages/game/simulation';import {COSMETICS,ratingChanges,type Mode,type Rules} from '../../packages/game/content';
try{process.loadEnvFile('.env.local');}catch{}
await initPhysics();
const dbKey=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_PUBLISHABLE_KEY;
const db=process.env.SUPABASE_URL&&dbKey?createClient(process.env.SUPABASE_URL,dbKey,{auth:{persistSession:false}}):null;
async function admin(body:Record<string,unknown>){const response=await fetch(`${process.env.SUPABASE_URL}/functions/v1/game-admin`,{method:'POST',headers:{'Content-Type':'application/json','x-game-server-token':process.env.GAME_SERVER_TOKEN||''},body:JSON.stringify(body)});const result=await response.json();return {data:response.ok?result:null,error:response.ok?null:{message:result.error||'Progress service unavailable'}};}
const identities=new Map<string,{id:string;name:string;created:number}>();const rooms=new Map<string,BattleRoom>();
async function identity(token?:string){if(!token)throw new Error('Choose a name before joining');const guest=identities.get(token);if(guest)return {id:guest.id,name:guest.name,account:false,rating:800};if(!db)throw new Error('Accounts are not configured yet');const {data,error}=await db.auth.getUser(token);if(error||!data.user)throw new Error('Sign in again to join');const {data:profile}=await db.from('profiles').select('*').eq('id',data.user.id).single();return {id:data.user.id,name:profile?.name||data.user.user_metadata.full_name||'Golfer',account:true,rating:profile?.rating||800};}
class BattleRoom extends Room{
 maxClients=8;game!:Game;owner='';code='';private tick=0;private rates=new Map<string,{at:number;n:number}>();private accountIds=new Map<string,{id:string;rating:number}>();private saved=false;
 async onCreate(options:{mode?:Mode;code?:string;rules?:Partial<Rules>;courseId?:string}){if(rooms.size>=1)throw new Error('The course is busy. Try again after this match.');const modes:Mode[]=['party','royale','ranked','custom'];const mode=modes.includes(options.mode!)?options.mode!:'party';this.game=new Game(mode,options.rules,Math.floor(Math.random()*100000));if(options.courseId&&mode==='custom'){const {COURSES}=await import('../../packages/game/content');const c=COURSES.find(c=>c.id===options.courseId);if(c){this.game.course=c;this.game.buildWorld();}}this.code=options.code||Math.random().toString(36).slice(2,8).toUpperCase();this.setState(new Schema());this.setMetadata({mode,code:this.code,private:mode==='custom'});if(mode==='custom')this.setPrivate(true);rooms.set(this.roomId,this);
 this.onMessage('input',(client,input:Input)=>{if(this.allow(client.sessionId))this.game.input(client.sessionId,input);});this.onMessage('action',(client,a:Action)=>{if(this.allow(client.sessionId)&&a&&typeof a.type==='string')this.game.action(client.sessionId,a);});this.onMessage('start',client=>{if(client.sessionId===this.owner&&this.game.mode==='custom')this.begin();});
 this.setFixedTimestep(()=>{this.game.tick();if(this.game.phase==='lobby'&&this.game.time>30&&this.clients.length&&(mode!=='ranked'||this.clients.length>=2))this.begin();if(++this.tick%3===0){this.broadcast('snapshot',{...this.game.snapshot(),roomCode:this.code});for(const event of this.game.events.splice(0))this.clients.find(c=>c.sessionId===event.playerId)?.send('notice',event.text);}if(this.game.resultsReady&&!this.saved){this.saved=true;void this.saveResults();}},60);}
 allow(id:string){const now=Date.now();const r=this.rates.get(id)||{at:now,n:0};if(now-r.at>1000){r.at=now;r.n=0;}r.n++;this.rates.set(id,r);return r.n<100;}
 async onAuth(_client:Client,options:{token?:string}){const person=await identity(options.token);if(this.game.mode==='ranked'&&!person.account)throw new Error('Google sign-in is required for Ranked');if(this.game.phase!=='lobby')throw new Error('This match has started');if([...this.accountIds.values()].some(p=>p.id===person.id))throw new Error('You already joined this match');if(this.game.mode==='ranked'){const first=[...this.accountIds.values()][0];if(first&&Math.abs(first.rating-person.rating)>Math.min(600,200+Math.floor(this.game.time/30)*100))throw new Error('No match in your rating range yet. Try again shortly.');}return person;}
 onJoin(client:Client,_options:unknown,auth:{id:string;name:string;account:boolean;rating:number}){if(!this.owner)this.owner=client.sessionId;if(auth.account)this.accountIds.set(client.sessionId,{id:auth.id,rating:auth.rating});this.game.addPlayer(client.sessionId,auth.name);client.send('welcome',{id:client.sessionId,code:this.code,owner:this.owner});client.send('snapshot',this.game.snapshot());if(this.clients.length===8)this.begin();}
 begin(){if(this.game.phase!=='lobby')return;if(this.game.mode==='ranked'&&this.clients.length<2)return;const target=this.game.mode==='royale'?8:this.game.mode==='custom'?Math.min(8,this.clients.length+this.game.rules.bots):4;const names=['Birdie','Chip','Bogey','Ace','Putter','Divot','Mulligan'];let b=0;while(this.game.mode!=='ranked'&&this.game.players.size<target)this.game.addPlayer(`bot-${b}`,names[b++]+' · BOT',true);this.game.start();void this.lock();}
 async onDrop(client:Client){const p=this.game.players.get(client.sessionId);if(p){p.connected=false;this.game.input(client.sessionId,{x:0,z:0,yaw:p.yaw,charging:false});}try{await this.allowReconnection(client,30);if(p)p.connected=true;}catch{this.depart(client);}}
 onLeave(client:Client){this.depart(client);}
 depart(client:Client){const p=this.game.players.get(client.sessionId);if(this.game.phase==='lobby')this.game.removePlayer(client.sessionId);else if(p){p.connected=false;p.finished=true;p.eliminated=true;p.input={x:0,z:0,yaw:0,charging:false};}if(!this.clients.length)void this.disconnect();}
 async saveResults(){if(!db||!this.accountIds.size)return;const humans=[...this.accountIds.entries()].map(([session,a])=>({id:a.id,rating:a.rating,score:this.game.players.get(session)?.score||0}));const changes=this.game.mode==='ranked'?ratingChanges(humans):[];const results=humans.map(p=>({user_id:p.id,score:p.score,rating_change:changes.find(c=>c.id===p.id)?.change||0,tokens:10+Math.min(30,Math.floor(p.score/10))}));for(let attempt=0;attempt<3;attempt++){const {error}=process.env.GAME_SERVER_TOKEN?await admin({operation:'finish',match_key:this.roomId,mode:this.game.mode,entries:results}):await db.rpc('finish_match',{match_key:this.roomId,match_mode:this.game.mode,entries:results});if(!error){this.broadcast('saved',{ok:true});return;}console.error('Result persistence failed:',error.message);await new Promise(r=>setTimeout(r,1000*(attempt+1)));}this.broadcast('saved',{ok:false});}
 onDispose(){rooms.delete(this.roomId);this.game.world.free();}
}
const app=express();app.use(cors({origin:process.env.WEB_ORIGIN?.split(',')||true}));app.use(express.json({limit:'8kb'}));const limits=new Map<string,{at:number;n:number}>();app.use('/api',(req,res,next)=>{const ip=req.ip||'local',now=Date.now();let l=limits.get(ip);if(!l||now-l.at>60000){l={at:now,n:0};limits.set(ip,l);}if(++l.n>120){res.status(429).json({error:'Take a breath. Try again in a moment.'});return;}next();});
app.get('/api/health',(_req,res)=>res.json({ok:true,rooms:rooms.size,accounts:!!db,version:'1.0.0'}));
app.post('/api/guest',(req,res)=>{const token=randomUUID();identities.set(token,{id:randomUUID(),name:String(req.body.name||'Golfer').slice(0,20),created:Date.now()});res.json({token});});
app.get('/api/rooms',(req,res)=>res.json([...rooms.values()].filter(r=>req.query.code?r.code===String(req.query.code).toUpperCase():r.game.mode!=='custom').map(r=>({id:r.roomId,code:r.code,mode:r.game.mode,phase:r.game.phase,players:r.clients.length}))));
app.get('/api/leaderboard',async(_req,res)=>{if(!db){res.json([]);return;}const {data,error}=await db.from('profiles').select('id,name,rating,matches,placements').order('rating',{ascending:false}).limit(50);if(error){res.status(503).json({error:'Leaderboard is resting. Try later.'});return;}res.json(data);});
app.get('/api/profile',async(req,res)=>{try{const i=await identity(req.headers.authorization?.replace('Bearer ',''));if(!i.account||!db){res.status(401).json({error:'Sign in to save progress'});return;}const {data}=await db.from('profiles').select('*').eq('id',i.id).single();res.json(data);}catch{res.status(401).json({error:'Sign in again'});}});
app.post('/api/unlock',async(req,res)=>{try{const i=await identity(req.headers.authorization?.replace('Bearer ',''));const cosmetic=COSMETICS.find(c=>c.id===req.body.id);if(!i.account||!db||!cosmetic){res.status(400).json({error:'Sign in and choose a cosmetic'});return;}const {data,error}=process.env.GAME_SERVER_TOKEN?await admin({operation:'unlock',user_token:req.headers.authorization?.replace('Bearer ',''),id:cosmetic.id}):await db.rpc('unlock_cosmetic',{who:i.id,cosmetic_id:cosmetic.id,price:cosmetic.cost});if(error){res.status(400).json({error:error.message});return;}res.json(data);}catch{res.status(401).json({error:'Sign in again'});}});
app.post('/api/equipment',async(req,res)=>{try{const token=req.headers.authorization?.replace('Bearer ','');const i=await identity(token);if(!i.account||!dbKey){res.status(401).json({error:'Sign in first'});return;}const ownDb=createClient(process.env.SUPABASE_URL!,dbKey,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const {error}=await ownDb.from('profiles').update({equipment:req.body.equipment}).eq('id',i.id);if(error){res.status(400).json({error:error.message});return;}res.json({ok:true});}catch{res.status(401).json({error:'Sign in again'});}});
const http=createServer(app);const server=new Server({transport:new WebSocketTransport({server:http}),greet:false});server.define('battle',BattleRoom).filterBy(['mode','code']);await server.listen(Number(process.env.PORT||2567),'0.0.0.0');console.log('Battle Golf server ready on port',process.env.PORT||2567);
setInterval(()=>{const now=Date.now();for(const [token,g] of identities)if(now-g.created>86400000)identities.delete(token);for(const [ip,l] of limits)if(now-l.at>60000)limits.delete(ip);},60000).unref();

